In [1]:
!pip install calfem-python

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.2/207.2 kB 3.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 13.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.8/38.8 MB 16.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.5/93.5 kB 9.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 53.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 MB 9.0 MB/s eta 0:00:00
  Created wheel for pyvtk: filename=PyVTK-0.5.18-py3-none-any.whl size=24735 sha256=d0b330477d3357e6f8414af1f4f44e44c56b7cdd876797c769dc99bb86b9a370
  Stored in directory: /root/.cache/pip/wheels/4e/e6/8b/58fdf3a1ffab592ded0e0ab8cc64e889dc3377a7a31d6174bc
  Created wheel for vedo: filename=vedo-2023.5.0-py3-none-any.whl size=2781551 sha256=ca9360729a0c4944a43be672e5947f2ccf5834e471e420f759d4245bc2bac313
  Stored in directory: /root/.

In [2]:
import numpy as np
import calfem.core as cfc

e = int(input("Enter the number of Elements: "))
n = int(input("Enter the number of Nodes: "))
K = np.zeros((n, n))
f = np.zeros((n, 1))
Edof = np.zeros((e, 2), dtype=int)  # Initialize Edof array

# Getting input for node to node history
for i in range(e):
    val_1 = int(input(f"Enter initial node number of element {i + 1} = "))
    val_2 = int(input(f"Enter final node number of element {i + 1} = "))
    Edof[i] = [val_1, val_2]

# Assemble the K matrix based on user input
for i in range(e):
    stiffness_value = float(input(f"Enter stiffness value for element K{i + 1} as 'N/mm' = "))
    element_stiffness = cfc.spring1e(stiffness_value)
    cfc.assem(Edof[i], K, element_stiffness)

# Getting input for node Force history
for i in range(n):
    a = float(input(f"Enter node {i + 1} force as N = "))
    f[i] = a

b = int(input("Enter the number of supports = "))

bc = np.zeros(b, dtype=int)

for i in range(b):
    element = int(input(f"Enter support {i + 1} node number = "))
    bc[i] = element

U,F =cfc.solveq(K,f,bc)

print(f"\nGlobal Stiffness Matrix\n\n{K}\n\nForce Vector\n\n{f}\n\nDisplacement\n\n{np.around(U, decimals=3)}\n\nForce\n\n{np.around(F, decimals=3)}")

Enter the number of Elements: 3
Enter the number of Nodes: 3
Enter initial node number of element 1 = 1
Enter final node number of element 1 = 2
Enter initial node number of element 2 = 2
Enter final node number of element 2 = 3
Enter initial node number of element 3 = 2
Enter final node number of element 3 = 3
Enter stiffness value for element K1 as 'N/mm' = 100
Enter stiffness value for element K2 as 'N/mm' = 150
Enter stiffness value for element K3 as 'N/mm' = 75
Enter node 1 force as N = 0
Enter node 2 force as N = 200
Enter node 3 force as N = 0
Enter the number of supports = 2
Enter support 1 node number = 1
Enter support 2 node number = 3

Global Stiffness Matrix

[[ 100. -100.    0.]
 [-100.  325. -225.]
 [   0. -225.  225.]]

Force Vector

[[  0.]
 [200.]
 [  0.]]

Displacement

[[0.   ]
 [0.615]
 [0.   ]]

Force

[[ -61.538]
 [   0.   ]
 [-138.462]]
